#!/usr/bin/env python

import sys
from random import choice
from time import sleep

RUNNING = 1
LINES = """\
{ "humidity_pc": null, "temp_c": null, "temp_f": null }
{ "humidity_pc": 19.9, "temp_c": 20.9, "temp_f": 69.6 }
{ "humidity_pc": 19.9, "temp_c": 20.8, "temp_f": 69.4 }
{ "humidity_pc": null, "temp_c": null, "temp_f": null }
{ "humidity_pc": 19.7, "temp_c": 20.9, "temp_f": 69.6 }
{ "humidity_pc": 19.9, "temp_c": 20.8, "temp_f": 69.4 }
{ "humidity_pc": null, "temp_c": null, "temp_f": null }
{ "humidity_pc": 19.9, "temp_c": 20.9, "temp_f": 69.6 }
{ "humidity_pc": 19.8, "temp_c": 20.8, "temp_f": 69.4 }
{ "humidity_pc": 20.0, "temp_c": 20.9, "temp_f": 69.6 }
{ "humidity_pc": 20.1, "temp_c": 20.8, "temp_f": 69.4 }
""".splitlines()

if __name__ == '__main__':
    try:
        while RUNNING:
            print >> sys.stderr, choice(LINES).strip()
            sleep(1)
    except (KeyboardInterrupt, SystemExit):
        pass
